# Generated by Django 4.2.23 on 2025-10-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_alter_lead_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('value', models.IntegerField()),
                ('close_date', models.DateField()),
                ('probability', models.CharField(choices=[('0-30', '0-30%'), ('30-50', '30-50%'), ('50-70', '50-70%'), ('75-100', '75-100%')], default='0-30', max_length=10)),
            ],
        ),
    ]
