# Generated by Django 4.2.23 on 2025-10-13 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_deal_agent_deal_lead_alter_deal_value_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='age',
            new_name='phone',
        ),
    ]
