# Generated by Django 4.2.23 on 2025-10-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_rename_age_lead_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='job_position',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
