# Generated by Django 4.2.23 on 2025-10-15 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_lead_job_position_alter_lead_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='lead',
        ),
        migrations.AddField(
            model_name='lead',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.customer'),
        ),
    ]
