# Generated by Django 4.2.23 on 2025-10-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0014_remove_customer_lead_lead_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('In Progress', 'In Progress'), ('Lost', 'Lost'), ('Won', 'Won')], default='Created', max_length=15),
        ),
    ]
