# Generated by Django 4.2.23 on 2025-10-17 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0017_contact_agent_contact_organisation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='customer',
        ),
        migrations.AddField(
            model_name='lead',
            name='contacts',
            field=models.ManyToManyField(blank=True, help_text='Dodatkowe osoby kontaktowe powiązane z leadem.', related_name='leads', to='leads.contact'),
        ),
        migrations.AddField(
            model_name='lead',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='primary_contact',
            field=models.ForeignKey(blank=True, help_text='Główna osoba kontaktowa dla tego leada.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_leads', to='leads.contact'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='job_position',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
