# Generated by Django 4.2.23 on 2025-10-17 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0018_remove_contact_agent_remove_contact_lead_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.lead'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='leads', to='leads.contact'),
        ),
    ]
