# Generated by Django 4.2.23 on 2025-10-18 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0020_contact_agent_alter_lead_primary_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.contact'),
        ),
    ]
