# Generated by Django 4.2.23 on 2025-10-29 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0021_deal_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='leads.contact'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='leads.lead'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
