# Generated by Django 4.2.23 on 2025-11-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0022_alter_deal_contact_alter_deal_lead_alter_deal_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='category',
        ),
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('regular', 'Regular'), ('low', 'Low')], default='regular', max_length=10),
        ),
    ]
