# Generated by Django 4.2.23 on 2025-11-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0023_remove_lead_category_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('New', 'new'), ('Regular', 'regular'), ('Low', 'row')], default='Regular', max_length=10),
        ),
    ]
