# Generated by Django 4.2.23 on 2025-11-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0024_alter_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Regular', 'Regular'), ('Key', 'Key')], default='Regular', max_length=10),
        ),
    ]
